spring:
  application:
    name: riskboard

  datasource:
    url: jdbc:h2:mem:riskboard;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

# Autorise le frontend Angular (dev server) a appeler l'API
riskboard:
  cors:
    allowed-origins: http://localhost:4200
